[phases.setup]
nixPkgs = [
  "php",
  "phpExtensions.curl",
  "phpExtensions.gd",
  "phpExtensions.mbstring",
  "phpExtensions.mysqli",
  "phpExtensions.pdo",
  "phpExtensions.zip",
  "phpPackages.composer"
]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["echo 'PHP application built successfully'"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public public/index.php" 