[phases.setup]
nixPkgs = ["php", "php-pdo", "php-mysql", "php-mbstring", "php-json", "php-curl", "php-gd", "php-zip", "phpPackages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["echo 'PHP application built successfully'"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public public/index.php" 